# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('grade', models.CharField(max_length=10, verbose_name='班级')),
                ('course', models.CharField(max_length=32, verbose_name='课程')),
                ('enroll_date', models.DateField(default=datetime.datetime.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
